set-option -g mouse on
set-option -s set-clipboard off
set-option -g mode-keys vi
set-option -g allow-rename off
set-option -g history-limit 100000

# sane split/new-window options
bind-key c  new-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

#bind-key -T copy-mode-vi 'v' send -X begin-selection
#bind-key -T copy-mode-vi 'y' send -X copy-pipe "xclip -i -sel clipboard"\; send -X clear-selection
#bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel "xclip -selection clipboard -i"

set -g default-terminal "screen-256color"
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @yank_selection_mouse 'clipboard'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
